---
- hosts: ubuntu@110.110.112.253
  roles:
     - role: dj-wasabi.zabbix-agent
       agent_server: 110.110.112.256
       agent_serveractive: 110.110.112.256
       zabbix_url: http://110.110.112.256/zabbix
       zabbix_api_use: true # use zabbix_api_create_host and/or zabbix_api_create_hostgroup from 0.8.0
       zabbix_api_user: Admin
       zabbix_api_pass: zabbix
       zabbix_create_host: present
       zabbix_host_groups:
         - Linux Servers
       zabbix_link_templates:
         - Template OS Linux
         - Apache APP Template
      # zabbix_macros:
       #  - macro_key: apache_type
        #   macro_value: reverse_proxy

